version: "3"

services:
  api:
    depends_on:
      - mongo
      - broker
    container_name: api
    build: ./smart-sheet-service
    command: yarn run start
    ports:
      - "3006:3006"
    environment:
      - DATABASE_URL=mongodb://mongo/smart-sheet
      - PORT=3006
    networks:
      - smartsheet-network
  pubsub:
    depends_on:
      - broker
      - api
    container_name: pubsub
    build: ./smart-sheet-pubsub
    command: yarn run start
    networks:
      - smartsheet-network
  broker:
    image: eclipse-mosquitto:1.6.13
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - smartsheet-network
  mongo:
    container_name: db_code
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017
    networks:
      - smartsheet-network
  front:
    depends_on:
      - api
    container_name: front
    build: ./smart-sheet-app
    command: yarn run start
    ports:
      - "3000:3000"
    networks:
      - smartsheet-network

  nginx:
    depends_on:
      - api
      - front
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - smartsheet-network

volumes:
  mongodata:
networks:
  smartsheet-network:
    driver: bridge
